language: go
go:
- 1.13.x
go_import_path: k8s.io/ingress-nginx
services:
- docker
env:
  global:
  - REGISTRY=index.docker.io/shopify
  - secure: NsGaD0ec8w/fILGLxTpxt0aiPYp0K5/7y/OQG/U6VkULQx1CmFHcSJtXtNZ6OCia5szlCNCNm5cXueFFOhBMXa0NGT6FKGKJU3HdjRaqo6APCau0dsW2+HNc0alRoVuqmgqLHnDihXspVapHwNlZqbIs/I5IahzUA9dMSdkssf2AG4BsF5/JC5fq8jzZdhooDUrL93681LO4SEfB2FmlGnDWQJg9rQdvhmfwJDyOmJFb0JqDr8T87N/fFomUwHDRBOrU2NGC3rs+E4Uilo2oVDnM1viSzBruwsUUl3FeYx6F+O/lJfw7sAjNUInV1gQ3U9+Lhrh3b1SqNTaiwdntirWlRiYzWrDOV96LQdFPqTb371d3xYI5bRRuSQ2s9ra1IU7oJHmJGOrZ7vwRvMaq3ogPtRcyF24+pD+Z4P3Sg3DFixcFwRbyth5Nr86298RX680yb1TAqWGGdThQ4ONdbJdT/TUDDOh+lv3wnooZEb1jfAVEzkCQM0j3PNQwIh9vucGg+GWi4qBbxlLyF6lP2pbNpmsA1ORaOsNIMy/DisDjmVyQUuKTRIpxigbjEOdYelpifDIYeJL98neE51mN5Xu5DoFP6MK2a2/Fva5EB8/UKXXMbNPHmba6N+fwAexg3xyl9S3EruPZjVDGh+9zuREulB/RRvaFx+8p3qcHCAk=
  - secure: k8hjJCXnCiVjRmpW/g/Vwv0m29hZQCDA6tT9pzkWQFgf0WHzCBolwZ8cwqjRewoyOLU2VSjklDWtoUSHWUXrj9u9y8r01ogwvdWKWbq0Krwse/iqHeZL5EPD8kT+n4yoKy0ek5FH0CXONWF5wi4BRMh48XucRGAYUrePhFx0FwkK+WJE3GFHcWfSiBy1lBXtJRtm5lXDzZWkYixch/7jZnxcReZSEKzcYWrHXVCOzNcKgYuIOlbCwXqd5cbdxyY9wTCQdtlmJXf8HbjfO/O5YN5t06SCL2j+Qz8+wOmG4CIA5C1hZLH0z6gBD+2hEaqD8pDpfbNZxqjdUe+xEwGiFyFRCHUWjrs5ZIrMjVz/9kSDvzIWKBR8IhqV96KP054qIJuz8iFGTpFV4ytl9cSwOdYdh783kbWuJl2tzQzH9CaeMa93MWK9iE6ItiocmsN/tg+UN236s0BAjqkeg+Brb4WPB3a+Xwr61Bofn9pwk15PIajE9ycBPGtAPvTk7HMB/W1b7s8YiyAwCjb6yaTo1RX/IeFIh7K1HhbiWca24wxxDe4E1VZEu6/NClkMO1kDaLOlQRyrO10bq6s1cP17poyqlIjPmYXgRQEp5Q01kAaPYNylh8/cDsV5SO6cX39d/Hvzf32670aeC+t5p/0BRkcTMjUCU+0Jpum/frMbKl8=
jobs:
  include:
  - stage: Static Check
    script:
    - build/run-in-docker.sh make static-check
  - stage: Lua Unit Test
    script:
    - build/run-in-docker.sh make lua-test
  - stage: Go Unit Test
    script:
    - build/run-in-docker.sh make test
  - stage: e2e
    if: commit_message !~ /(skip-e2e)/
    before_script:
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s
      https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
    - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-linux-amd64
      && chmod +x kind && sudo mv kind /usr/local/bin/
    - go get github.com/onsi/ginkgo/ginkgo
    script: make kind-e2e-test
  - stage: publish amd64
    if: type = push AND branch = master AND repo = Shopify/ingress
    script:
    - ".travis/publish.sh amd64"
