dist: trusty

sudo: required

services:
  - docker

# FIXME(#46924): these two commands are required to enable IPv6,
# they shouldn't exist, please revert once more official solutions appeared.
# see https://github.com/travis-ci/travis-ci/issues/8891#issuecomment-353403729
before_install:
  - echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

language: generic

notifications:
  email:
    on_failure: always
    on_success: never

# New secure variables can be added using travis encrypt -r kubernetes/ingress-nginx --add K=V
env:
  global:
  - DOCKER=docker
  - SKIP_SNAPSHOT=true
  - NODE_IP=10.192.0.3
  - E2E_NODES=6
  - GH_REF=github.com/kubernetes/ingress-nginx

jobs:
  include:
  - stage: publish amd64
    if: type = push AND repo = Shopify/ingress
    script:
    - COMPONENT=nginx .travis/publish.sh amd64
