dist: trusty

sudo: required

services:
  - docker

language: generic

notifications:
  email:
    on_failure: always
    on_success: never

# New secure variables can be added using travis encrypt -r kubernetes/ingress-nginx --add K=V
env:
  global:
  - CHANGE_MINIKUBE_NONE_USER=true
  - KUBERNETES_VERSION=v1.10.0
  - DOCKER=docker
  - GH_REF=github.com/kubernetes/ingress-nginx

jobs:
  include:
  - stage: Static Check
    script:
    - make static-check
  - stage: Lua Unit Test
    script:
    - make lua-test
  - stage: Coverage
    before_script:
    # start minikube
    - test/e2e/up.sh
    script:
    - make cover
  - stage: e2e
    before_script:
    - test/e2e/up.sh
    - SKIP_MINIKUBE_START=true make dev-env
    script:
    - make e2e-test
  # split builds to avoid job timeouts
  - stage: publish amd64
    if: type = push AND branch = master AND repo = Shopify/ingress
    script:
    - .travis/publish.sh amd64
  - stage: publish arm
    if: type = api AND branch = master AND repo = kubernetes/ingress-nginx
    script:
    - make register-qemu
    - .travis/publish.sh arm
  - stage: publish arm64
    if: type = api AND branch = master AND repo = kubernetes/ingress-nginx
    script:
    - make register-qemu
    - .travis/publish.sh arm64
  - stage: publish ppc64le
    if: type = api AND branch = master AND repo = kubernetes/ingress-nginx
    script:
    - make register-qemu
    - .travis/publish.sh ppc64le
  - stage: publish s390x
    if: type = api AND branch = master AND repo = kubernetes/ingress-nginx
    script:
    - make register-qemu
    - .travis/publish.sh s390x
  - stage: Publish docs
    if: type = api AND branch = master AND repo = kubernetes/ingress-nginx
    script:
    - .travis/publish-docs.sh
