/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	ingressnginxpluginv1alpha1 "k8s.io/ingress-nginx/pkg/apis/ingressnginxplugin/v1alpha1"
	versioned "k8s.io/ingress-nginx/pkg/client/clientset/versioned"
	internalinterfaces "k8s.io/ingress-nginx/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "k8s.io/ingress-nginx/pkg/client/listers/ingressnginxplugin/v1alpha1"
)

// IngressNginxPluginInformer provides access to a shared informer and lister for
// IngressNginxPlugins.
type IngressNginxPluginInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IngressNginxPluginLister
}

type ingressNginxPluginInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIngressNginxPluginInformer constructs a new informer for IngressNginxPlugin type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIngressNginxPluginInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIngressNginxPluginInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIngressNginxPluginInformer constructs a new informer for IngressNginxPlugin type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIngressNginxPluginInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NginxV1alpha1().IngressNginxPlugins(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NginxV1alpha1().IngressNginxPlugins(namespace).Watch(options)
			},
		},
		&ingressnginxpluginv1alpha1.IngressNginxPlugin{},
		resyncPeriod,
		indexers,
	)
}

func (f *ingressNginxPluginInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIngressNginxPluginInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ingressNginxPluginInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ingressnginxpluginv1alpha1.IngressNginxPlugin{}, f.defaultInformer)
}

func (f *ingressNginxPluginInformer) Lister() v1alpha1.IngressNginxPluginLister {
	return v1alpha1.NewIngressNginxPluginLister(f.Informer().GetIndexer())
}
