/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/ingress-nginx/pkg/apis/ingressnginxplugin/v1alpha1"
)

// FakeIngressNginxPlugins implements IngressNginxPluginInterface
type FakeIngressNginxPlugins struct {
	Fake *FakeNginxV1alpha1
	ns   string
}

var ingressnginxpluginsResource = schema.GroupVersionResource{Group: "nginx.ingress.kubernetes.io", Version: "v1alpha1", Resource: "ingressnginxplugins"}

var ingressnginxpluginsKind = schema.GroupVersionKind{Group: "nginx.ingress.kubernetes.io", Version: "v1alpha1", Kind: "IngressNginxPlugin"}

// Get takes name of the ingressNginxPlugin, and returns the corresponding ingressNginxPlugin object, and an error if there is any.
func (c *FakeIngressNginxPlugins) Get(name string, options v1.GetOptions) (result *v1alpha1.IngressNginxPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ingressnginxpluginsResource, c.ns, name), &v1alpha1.IngressNginxPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressNginxPlugin), err
}

// List takes label and field selectors, and returns the list of IngressNginxPlugins that match those selectors.
func (c *FakeIngressNginxPlugins) List(opts v1.ListOptions) (result *v1alpha1.IngressNginxPluginList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ingressnginxpluginsResource, ingressnginxpluginsKind, c.ns, opts), &v1alpha1.IngressNginxPluginList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IngressNginxPluginList{ListMeta: obj.(*v1alpha1.IngressNginxPluginList).ListMeta}
	for _, item := range obj.(*v1alpha1.IngressNginxPluginList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ingressNginxPlugins.
func (c *FakeIngressNginxPlugins) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ingressnginxpluginsResource, c.ns, opts))

}

// Create takes the representation of a ingressNginxPlugin and creates it.  Returns the server's representation of the ingressNginxPlugin, and an error, if there is any.
func (c *FakeIngressNginxPlugins) Create(ingressNginxPlugin *v1alpha1.IngressNginxPlugin) (result *v1alpha1.IngressNginxPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ingressnginxpluginsResource, c.ns, ingressNginxPlugin), &v1alpha1.IngressNginxPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressNginxPlugin), err
}

// Update takes the representation of a ingressNginxPlugin and updates it. Returns the server's representation of the ingressNginxPlugin, and an error, if there is any.
func (c *FakeIngressNginxPlugins) Update(ingressNginxPlugin *v1alpha1.IngressNginxPlugin) (result *v1alpha1.IngressNginxPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ingressnginxpluginsResource, c.ns, ingressNginxPlugin), &v1alpha1.IngressNginxPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressNginxPlugin), err
}

// Delete takes name of the ingressNginxPlugin and deletes it. Returns an error if one occurs.
func (c *FakeIngressNginxPlugins) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ingressnginxpluginsResource, c.ns, name), &v1alpha1.IngressNginxPlugin{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIngressNginxPlugins) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ingressnginxpluginsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.IngressNginxPluginList{})
	return err
}

// Patch applies the patch and returns the patched ingressNginxPlugin.
func (c *FakeIngressNginxPlugins) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IngressNginxPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ingressnginxpluginsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IngressNginxPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IngressNginxPlugin), err
}
