/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/ingress-nginx/pkg/apis/ingressnginxplugin/v1alpha1"
	scheme "k8s.io/ingress-nginx/pkg/client/clientset/versioned/scheme"
)

// IngressNginxPluginsGetter has a method to return a IngressNginxPluginInterface.
// A group's client should implement this interface.
type IngressNginxPluginsGetter interface {
	IngressNginxPlugins(namespace string) IngressNginxPluginInterface
}

// IngressNginxPluginInterface has methods to work with IngressNginxPlugin resources.
type IngressNginxPluginInterface interface {
	Create(*v1alpha1.IngressNginxPlugin) (*v1alpha1.IngressNginxPlugin, error)
	Update(*v1alpha1.IngressNginxPlugin) (*v1alpha1.IngressNginxPlugin, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IngressNginxPlugin, error)
	List(opts v1.ListOptions) (*v1alpha1.IngressNginxPluginList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IngressNginxPlugin, err error)
	IngressNginxPluginExpansion
}

// ingressNginxPlugins implements IngressNginxPluginInterface
type ingressNginxPlugins struct {
	client rest.Interface
	ns     string
}

// newIngressNginxPlugins returns a IngressNginxPlugins
func newIngressNginxPlugins(c *NginxV1alpha1Client, namespace string) *ingressNginxPlugins {
	return &ingressNginxPlugins{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ingressNginxPlugin, and returns the corresponding ingressNginxPlugin object, and an error if there is any.
func (c *ingressNginxPlugins) Get(name string, options v1.GetOptions) (result *v1alpha1.IngressNginxPlugin, err error) {
	result = &v1alpha1.IngressNginxPlugin{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IngressNginxPlugins that match those selectors.
func (c *ingressNginxPlugins) List(opts v1.ListOptions) (result *v1alpha1.IngressNginxPluginList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IngressNginxPluginList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ingressNginxPlugins.
func (c *ingressNginxPlugins) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a ingressNginxPlugin and creates it.  Returns the server's representation of the ingressNginxPlugin, and an error, if there is any.
func (c *ingressNginxPlugins) Create(ingressNginxPlugin *v1alpha1.IngressNginxPlugin) (result *v1alpha1.IngressNginxPlugin, err error) {
	result = &v1alpha1.IngressNginxPlugin{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		Body(ingressNginxPlugin).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ingressNginxPlugin and updates it. Returns the server's representation of the ingressNginxPlugin, and an error, if there is any.
func (c *ingressNginxPlugins) Update(ingressNginxPlugin *v1alpha1.IngressNginxPlugin) (result *v1alpha1.IngressNginxPlugin, err error) {
	result = &v1alpha1.IngressNginxPlugin{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		Name(ingressNginxPlugin.Name).
		Body(ingressNginxPlugin).
		Do().
		Into(result)
	return
}

// Delete takes name of the ingressNginxPlugin and deletes it. Returns an error if one occurs.
func (c *ingressNginxPlugins) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ingressNginxPlugins) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ingressNginxPlugin.
func (c *ingressNginxPlugins) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IngressNginxPlugin, err error) {
	result = &v1alpha1.IngressNginxPlugin{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ingressnginxplugins").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
